import type {
  CephalomedullaryNailInput,
  DistalRadiusOrifInput,
  DynamicHipScrewInput,
  OrthopaedicCommonInput,
} from "../../src/domain/types.ts";

export const completeTnoCommon: OrthopaedicCommonInput = {
  operationDateTime: "2026-07-20T09:10",
  surgeon: "Synthetic Surgeon A",
  assistant: "Synthetic Assistant B",
  supervisingConsultant: "Synthetic Consultant C",
  anaesthetic: "GA",
  anaesthetist: "Synthetic Anaesthetist D",
  indication: "Synthetic fracture indication",
  findings: "Synthetic fracture findings",
  bloodLoss: "100 mL",
  complications: "none",
  antibioticProphylaxis: "Synthetic antibiotic entry",
  dvtProphylaxis: "Synthetic DVT entry",
  postOpPlan: "Synthetic other postoperative instructions",
  additionalOperativeDetails: "Synthetic additional operative details",
  additionalTeamMembers: [],
  caseClassification: "Non-elective",
  side: "Left",
  operativeDiagnosis: "Synthetic operative diagnosis",
  positionAndTableSetup: "Synthetic position and table setup",
  tourniquetUsed: "no",
  tourniquetSite: "",
  tourniquetPressure: "",
  tourniquetDuration: "",
  imageIntensifierUsed: "yes",
  finalImagingFindings: "Synthetic final imaging findings",
  additionalProcedurePerformed: "no",
  additionalProcedureDetails: "",
  additionalProcedureReason: "",
  specimensOrSamples: "",
  tissueDetails: "Synthetic tissue detail",
  implantsUsed: "yes",
  implants: [{
    id: "synthetic-implant-1",
    component: "Synthetic component",
    manufacturer: "Synthetic manufacturer",
    productOrSystem: "Synthetic system",
    size: "Synthetic size",
    lotSerialOrReference: "SYN-REF-100",
  }],
  haemostasisDetails: "Synthetic haemostasis detail",
  closureDetails: "Synthetic closure detail",
  dressingAndImmobilisation: "Synthetic dressing and immobilisation",
  loadingInstructions: "Synthetic loading instruction",
  postoperativeMonitoring: "Synthetic monitoring instruction",
  postoperativeImaging: "Synthetic postoperative imaging plan",
  woundCare: "Synthetic wound-care instruction",
  followUp: "Synthetic follow-up plan",
  rehabilitationPlan: "Synthetic rehabilitation plan",
};

export const completeDhsInput: DynamicHipScrewInput = {
  ...completeTnoCommon,
  procedureId: "dynamic-hip-screw",
  findings: "Synthetic intertrochanteric fracture findings",
  dhsFracturePattern: "Synthetic intertrochanteric fracture pattern",
  dhsReductionMethod: "Closed reduction",
  dhsReductionDetails: "Synthetic closed reduction detail",
  dhsApproachAndIncision: "Synthetic lateral approach and incision",
  dhsGuidewireAndLagScrewDetails: "Synthetic guidewire and lag-screw placement",
  dhsPlateFixationDetails: "Synthetic side-plate and screw fixation",
  dhsCompressionApplied: "yes",
  dhsIrrigationDetails: "Synthetic irrigation detail",
};

export const completeCmnInput: CephalomedullaryNailInput = {
  ...completeTnoCommon,
  procedureId: "cephalomedullary-nail",
  findings: "Synthetic subtrochanteric fracture findings",
  cmnFracturePattern: "Synthetic subtrochanteric fracture pattern",
  cmnReductionMethod: "Combined closed and open reduction",
  cmnReductionDetails: "Synthetic combined reduction detail",
  cmnEntryPointAndIncision: "Synthetic entry point, approach and incision",
  cmnCanalPreparation: "Synthetic canal preparation",
  cmnNailInsertionDetails: "Synthetic nail insertion detail",
  cmnProximalFixationDetails: "Synthetic proximal fixation detail",
  cmnDistalLockingPerformed: "yes",
  cmnDistalLockingDetails: "Synthetic distal locking detail",
  cmnCompressionApplied: "not applicable",
  cmnIrrigationDetails: "Synthetic irrigation detail",
};

export const completeDistalRadiusInput: DistalRadiusOrifInput = {
  ...completeTnoCommon,
  procedureId: "distal-radius-orif",
  side: "Right",
  findings: "Synthetic distal radius fracture findings",
  distalRadiusFracturePattern: "Synthetic intra-articular fracture pattern",
  distalRadiusApproach: "Volar",
  distalRadiusApproachAndIncision: "Synthetic volar approach and incision",
  distalRadiusReductionDetails: "Synthetic reduction detail",
  distalRadiusFixationDetails: "Synthetic plate and screw fixation",
  distalRadiusDrujAssessed: "yes",
  distalRadiusDrujDetails: "Synthetic DRUJ assessment findings",
  distalRadiusTendonAssessment: "Synthetic tendon assessment",
  distalRadiusIrrigationDetails: "Synthetic irrigation detail",
};
