import type { OutputMode, ProcedureDefinition, ProcedureId } from "./types.ts";

const OUTPUT_MODES: readonly OutputMode[] = ["full", "postOp", "handover"];

export const PROCEDURE_DEFINITIONS: Readonly<Record<ProcedureId, ProcedureDefinition>> = {
  "lap-appendicectomy": {
    id: "lap-appendicectomy",
    label: "Laparoscopic appendicectomy",
    specialty: "general-surgery",
    category: "Emergency general surgery",
    keywords: ["appendix", "appendicitis", "laparoscopic"],
    completionProfile: "general-surgery",
    supportedOutputModes: OUTPUT_MODES,
  },
  "lap-cholecystectomy": {
    id: "lap-cholecystectomy",
    label: "Laparoscopic cholecystectomy",
    specialty: "general-surgery",
    category: "Biliary surgery",
    keywords: ["gallbladder", "biliary", "laparoscopic"],
    completionProfile: "general-surgery",
    supportedOutputModes: OUTPUT_MODES,
  },
  "diagnostic-laparoscopy": {
    id: "diagnostic-laparoscopy",
    label: "Diagnostic laparoscopy +/- washout / adhesiolysis",
    specialty: "general-surgery",
    category: "Laparoscopy",
    keywords: ["laparoscopy", "washout", "adhesiolysis"],
    completionProfile: "general-surgery",
    supportedOutputModes: OUTPUT_MODES,
  },
  "incision-and-drainage": {
    id: "incision-and-drainage",
    label: "Incision and drainage of abscess",
    specialty: "general-surgery",
    category: "Abscess surgery",
    keywords: ["abscess", "incision", "drainage"],
    completionProfile: "general-surgery",
    supportedOutputModes: OUTPUT_MODES,
  },
  "open-inguinal-hernia-repair": {
    id: "open-inguinal-hernia-repair",
    label: "Open inguinal hernia repair",
    specialty: "general-surgery",
    category: "Hernia surgery",
    keywords: ["inguinal", "hernia", "open"],
    completionProfile: "general-surgery",
    supportedOutputModes: OUTPUT_MODES,
  },
  "open-umbilical-hernia-repair": {
    id: "open-umbilical-hernia-repair",
    label: "Open umbilical hernia repair",
    specialty: "general-surgery",
    category: "Hernia surgery",
    keywords: ["umbilical", "hernia", "open"],
    completionProfile: "general-surgery",
    supportedOutputModes: OUTPUT_MODES,
  },
  "emergency-laparotomy": {
    id: "emergency-laparotomy",
    label: "Emergency laparotomy",
    specialty: "general-surgery",
    category: "Emergency general surgery",
    keywords: ["laparotomy", "emergency", "bowel"],
    completionProfile: "general-surgery",
    supportedOutputModes: OUTPUT_MODES,
  },
  "ankle-orif": {
    id: "ankle-orif",
    label: "Open reduction and internal fixation of ankle fracture",
    specialty: "trauma-orthopaedics",
    category: "Lower-limb trauma",
    keywords: ["ankle", "fracture", "ORIF", "malleolus", "syndesmosis"],
    completionProfile: "orthopaedics",
    supportedOutputModes: OUTPUT_MODES,
  },
  "hip-hemiarthroplasty": {
    id: "hip-hemiarthroplasty",
    label: "Hip hemiarthroplasty for fracture",
    specialty: "trauma-orthopaedics",
    category: "Hip-fracture surgery",
    keywords: ["hip", "hemiarthroplasty", "hemi", "neck of femur", "NOF"],
    completionProfile: "orthopaedics",
    supportedOutputModes: OUTPUT_MODES,
  },
  "dynamic-hip-screw": {
    id: "dynamic-hip-screw",
    label: "Dynamic hip screw fixation",
    specialty: "trauma-orthopaedics",
    category: "Hip-fracture surgery",
    keywords: ["hip", "DHS", "sliding hip screw", "trochanteric fracture"],
    completionProfile: "orthopaedics",
    supportedOutputModes: OUTPUT_MODES,
  },
  "cephalomedullary-nail": {
    id: "cephalomedullary-nail",
    label: "Cephalomedullary nail fixation",
    specialty: "trauma-orthopaedics",
    category: "Hip-fracture surgery",
    keywords: ["hip", "nail", "CMN", "IM nail", "cephalomedullary", "subtrochanteric"],
    completionProfile: "orthopaedics",
    supportedOutputModes: OUTPUT_MODES,
  },
  "distal-radius-orif": {
    id: "distal-radius-orif",
    label: "Open reduction and internal fixation of distal radius fracture",
    specialty: "trauma-orthopaedics",
    category: "Upper-limb trauma",
    keywords: ["wrist", "distal radius", "fracture", "ORIF", "volar plate"],
    completionProfile: "orthopaedics",
    supportedOutputModes: OUTPUT_MODES,
  },
};
